### PR TITLE
5.x Refactor

### PR DESCRIPTION
**Pull request by iksaku**
Refactored many things in the Source Code...
- Implemented a new OVHConfiguration class for better data referencing.
- Refactored OVHServiceProvider and OVHSwiftAdapter to properly use the new OVHConfiguration object.
- Refactored SetTempUrlKey command to simplify its readability.
- Adjusted Tests to comply with the new OVHConfiguration object.
- Overall Code cleanup.
- Comments FTW!

### CODE REVIEW

**Comment by iksaku** [comment]
Pending: #44

**Comment by iksaku** [comment]
@sausin suggestion...

Should I deprecate the use of StyleCI and opt for [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) instead?

This paired up with [Composer Git Hooks](https://github.com/BrainMaestro/composer-git-hooks) can allow for automatic style fixing before committing any changes, and can also be implemented in Github Actions for an extra check.

You can see an example of this combination in [one of my repos](https://github.com/iksaku/siase-wrapper). Specifically at `composer.json` and Github Actions.

**Comment by sausin** [comment]
@iksaku Wow, thanks a lot for all the work on this :+1: 

I really like all the changes, gives a good feel to the code when reading :smiley: 

Regarding deprecating StyleCI, I'm all for it! Saw the setup in your repo and it would be a good change. Only one thing regarding `php-cs-fixer` - as I understand it, they don't yet support [PSR-12](https://www.php-fig.org/psr/psr-12/) in the default setup (AFAIK) which superseded [PSR-2](https://www.php-fig.org/psr/psr-2/).

There are custom settings suggested in one of the issues threads over there. Not perfect, but does work mostly alright. Ideas?

Of course, StyleCI wasn't supporting it either, but if we're doing the changes it would be awesome to get it going together with it all.

**Comment by iksaku** [comment]
You’re right, `php-cs-fixer` is not yet ready for PSR-12, but there’s an [in-progress PR to support it](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4943).

I could start the integration and let ground ready for when PSR-12 is available for `php-cs-fixer`.

Besides this, would like you to check one or two times the changes to README.md, hope it’s pretty understandable.

**Comment by sausin** [comment]
Have done some touch-ups to the README.md. Thanks for documenting the `deleteAfter` method also :+1:

**Comment by iksaku** [comment]
Well, it looks like StyleCI will keep failing here because its still present in the master branch :sweat_smile:

**Comment by iksaku** [comment]
I'm pretty confident on what's done, will move out from Draft :crossed_fingers:

**Comment by sausin** [comment]
Was looking good to me as well, have done the merge :smiley:

**Comment by drupol** [comment]
Hi,

PSR12 is available for PHP CS Fixer through this [package](https://packagist.org/packages/drupol/phpcsfixer-configs-php).

You can use it like this: 

`./vendor/bin/php-cs-fixer  --dry-run --allow-risky=yes --config=./vendor/drupol/php-conventions/config/psr12/php_cs_fixer.config.php --using-cache=no --verbose fix
`

Feel free to let me know if you need more help.

**Pull request merged**
