### PR TITLE
Tests with PHP 8

### PR DESCRIPTION
**Pull request by sausin**

### CODE REVIEW

**Comment by sausin** [comment]
Without upstream dependencies supporting PHP 8, it seems support won't be possible as requested in #78

**Comment by Elycin** [comment]
Hey @sausin,

Thanks for making the attempt, I've left a comment over at https://github.com/php-opencloud/openstack/pull/325#issuecomment-809280717 asking if there's anything I can do to help contribute to accelerating the speed of upgrading that dependency. Hopefully, I'll hear something soon in regards to the active pull request (#325).

**Comment by sausin** [comment]
@Elycin Thanks and that's awesome! Appreciated :+1:

**Comment by Elycin** [comment]
Hey there, as of about two hours ago from the time I am writing this message, the dependent library has been updated.

**Comment by sausin** [comment]
@Elycin thanks for the update! It seems that a new release hasn't yet been tagged and so the tests are still failing. Let's hope one gets tagged soon

**Comment by Elycin** [comment]
Tagged! https://github.com/php-opencloud/openstack/releases/tag/v3.2.0

**Comment by sausin** [comment]
@Elycin Thank you for doing the followup there! I've had to update the test setup as there were quite a bit of errors due to `isArray()` [deprecation](https://php.watch/versions/8.0/deprecated-reflectionparameter-methods) in PHP 8.

While the older laravel versions will still 'work', it's probably better to tag 6.x on the package to bring clarity that older laravel verions won't be actively supported. 

Regarding `openstack`, a fork to maintain only for the purpose of this package's scope could be a good option. We can just focus on keeping it functional for a specific purpose and thereby limiting the effort needed on support. Unfortunately, I feel that I won't have the time to help out on the main `openstack` repository.

We can also take thoughts of @iksaku on this.

**Comment by sausin** [comment]
Have tagged `6.0.0`. We can still continue the discussion on the `openstack` here :-)

**Pull request merged**
