### PR TITLE
Improved Form Post

### PR DESCRIPTION
**Pull request by iksaku**

### CODE REVIEW

**Comment by iksaku** [comment]
So... There's no `isBefore` Carbon function for Laravel 5.8... :thinking:

**Comment by sausin** [comment]
Thank you for all the changes to the docs!

The other PR broke some of your changes unfortunately. If you could please fix the conflicts :smiley:

**Comment by sausin** [comment]
Also, we'd removed `Carbon` as a dependency sometime back. Of course, this being a laravel package the call to `now()` in the formsignature method won't break anything, but I was thinking it would be more consistent to not use it.

**Comment by iksaku** [comment]
@sausin Yeah, I remember removing dependency on `Carbon` from the package, and like you say, being a Laravel package, using `Illuminate\Support` will always provide `Carbon` as a dependency.

The move here could be, to either use PHP built-ins or to take advantage of `Carbon` being available anyways.

**Comment by iksaku** [comment]
For now, I will remove uses of Carbon, we can discuss this later on for another PR

**Comment by sausin** [comment]
@iksaku :+1:

**Pull request merged**
