### PR TITLE
Fix Temporary URL Generation

### PR DESCRIPTION
**Pull request by iksaku**

### CODE REVIEW

**Comment by sausin** [comment]
Makes sense!

Could we also remove the `nesbot/carbon` dependency then?

**Comment by iksaku** [comment]
Yeah, we could remove its dependency and rely entirely on `DateTimeInterface`.

Will do a full check tomorrow to ensure we can safely remove Carbon dependency.

**Comment by sausin** [comment]
:+1:

**Comment by iksaku** [comment]
Properly removed all dependencies on `nesbot/carbon` :zap:

**Comment by sausin** [comment]
Thanks!

**Pull request merged**
